version: 2
jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys
      - run:
          name: Build docker image
          command: docker build -t anypay .
      - run:
          name: Deploy To Server
          command: |
            ./push_to_docker.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_deploy
