version: '2'

services:
  blockcypher-callbacks:
    build:
      context: .
      dockerfile: ./servers/blockcypher/Dockerfile
    ports:
      - 8000:8000
    expose:
      - "8000"
  websockets:
    build:
      context: .
      dockerfile: ./servers/websocket/Dockerfile
    ports:
      - 3000:3000
    expose:
      - "3000"
  rest-api:
    build:
      context: .
      dockerfile: ./servers/rest_api/Dockerfile
    ports:
      - 3000:3000
    expose:
      - "3000"
  blockcypher-processor:
    build:
      context: .
      dockerfile: ./servers/processor/blockcypher/Dockerfile
  payment-processor:
    build:
      context: .
      dockerfile: ./servers/processor/payments/Dockerfile
  payouts-cron:
    build:
      context: .
      dockerfile: ./servers/dash_payouts/Dockerfile
  instantsend-monitor:
    build:
      context: .
      dockerfile: ./processes/dash_monitor/Dockerfile
  bitcoincash-monitor:
    build:
      context: .
      dockerfile: ./processes/bitcoincash-monitor/Dockerfile
