version: "3.9"
services:
  rabbi:
    build: .
    environment:
      AMQP_URL: amqp://anypay:letmein@rabbitmq/anypay
      DATABASE_URL: postgres://anypay:letmein@postgres/anypay
      NODE_ENV: development
    command: rabbi start
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      AMQP_URL: amqp://anypay:letmein@rabbitmq/anypay
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: anypay
      POSTGRES_DB: anypay
      POSTGRES_PASSWORD: letmein
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      DEFAULT_USER: anypay
      DEFAULT_PASS: letmein
      DEFAULT_VHOST: anypay

