version: '2'

services:
  blockcypher-callbacks:
    build:
      context: .
      dockerfile: ./servers/blockcypher/Dockerfile
    ports:
      - 8000:8000
    expose:
      - "8000"
  websockets:
    build:
      context: .
      dockerfile: ./servers/websocket/Dockerfile
    ports:
      - 3000:3000
    expose:
      - "3000"
  rest-api:
    build:
      context: .
      dockerfile: ./servers/rest_api/Dockerfile
    ports:
      - 3000:3000
    expose:
      - "3000"
  payment-processor:
    build:
      context: .
      dockerfile: ./servers/processor/Dockerfile
  webapp:
    build:
      context: .
      dockerfile: ./servers/webapp/anypay-dash/Dockerfile
    ports:
      - 5678:80
