version: "3.9"

services:

  typescript_backend:
    build: .
    ports:
      - "5200:5200"
    environment:  
      DATABASE_URL: postgres://user:password@postgres_database:5432/anypay_dev
      DEV_DATABASE_URL: postgres://user:password@postgres_database:5432/anypay_dev
      AMQP_URL: amqp://guest:guest@message_exchange:5672/
      HOST: 0.0.0.0
      PORT: 5200
    depends_on:
      - postgres_database
      - message_exchange

  frontend_webapp:
    image: "anypay/anypayx.com:master"
    ports:
      - "3200:8081"
    environment:
      NEXT_PUBLIC_API_BASE: ""
      API_BASE: "/v1/api"
    volumes:
      - type: bind
        source: .devops/webapp
        target: /opt/anypay
    command: npm run dev
    env_file: .devops/webapp/.env

    depends_on:
      - typescript_backend

  postgres_database:
    image: "postgis/postgis"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=anypay_dev
    volumes:
      - ./.devops/postgresql/data:/var/lib/postgresql/data

  message_exchange:
    container_name: message_exchange
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/

  wallet_bot:
    image: "anypay/wallet-bot:master"
    ports:
      - "5201:5200"
    environment:
      - api_base=http://typescript_backend:5200
    env_file: .devops/walletbot/.env
    depends_on:
      - typescript_backend
    
