version: '3.8'

services:
  # Node.js service
  nodejs:
    image: node:18
    container_name: nodejs-app
    #volumes:
    #  - ./app:/app
    #working_dir: /app
    command: /bin/sh -c "npm install && npm run build && npm start"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      POSTGRES_URL: postgres://postgres:password@postgres:5432/mydatabase
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

  # PostgreSQL service
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP port

volumes:
  postgres_data:
