
class Chef::Recipe::Anypay

  def self.env
    [
      "AMQP_URL=#{data_bag_item('anypay', 'api')['AMQP_URL']}",
      "DATABASE_URL=#{data_bag_item('anypay', 'api')['DATABASE_URL']}",
      "AWS_ACCESS_KEY_ID=#{data_bag_item('anypay', 'api')['AWS_ACCESS_KEY_ID']}",
      "AWS_SECRET_ACCESS_KEY=#{data_bag_item('anypay', 'api')['AWS_SECRET_ACCESS_KEY']}",
      "BLOCKCYPHER_TOKEN=#{data_bag_item('anypay', 'api')['BLOCKCYPHER_TOKEN']}",
      "FORWARDING_SERVICE_URL=#{data_bag_item('anypay', 'api')['FORWARDING_SERVICE_URL']}",
      "DASH_CORE_PASSWORD=#{data_bag_item('anypay', 'api')['DASH_CORE_PASSWORD']}",
      "DASH_CORE_USER=#{data_bag_item('anypay', 'api')['DASH_CORE_USER']}",
      "ANYPAY_FIXER_ACCESS_KEY=#{data_bag_item('anypay', 'api')['ANYPAY_FIXER_ACCESS_KEY']}",
      "HOST=#{data_bag_item('anypay', 'api')['HOST']}",
      "NODE_ENV=#{data_bag_item('anypay', 'api')['NODE_ENV']}",
      "LIGHTNING_SERVICE=#{data_bag_item('anypay', 'api')['LIGHTNING_SERVICE']}",
      "BCH_RPC_HOST=#{data_bag_item('anypay', 'api')['BCH_RPC_HOST']}",
      "BCH_RPC_PORT=#{data_bag_item('anypay', 'api')['BCH_RPC_PORT']}",
      "BCH_RPC_USER=#{data_bag_item('anypay', 'api')['BCH_RPC_USER']}",
      "BCH_RPC_PASSWORD=#{data_bag_item('anypay', 'api')['BCH_RPC_PASSWORD']}",
      "ZENCASH_ZEROMQ_URL=#{data_bag_item('anypay', 'api')['ZENCASH_ZEROMQ_URL']}",
      "ZEN_RPC_HOST=#{data_bag_item('anypay', 'api')['ZEN_RPC_HOST']}",
      "ZEN_RPC_USER=#{data_bag_item('anypay', 'api')['ZEN_RPC_USER']}",
      "ZEN_RPC_PASSWORD=#{data_bag_item('anypay', 'api')['ZEN_RPC_PASSWORD']}",
      "ZEN_RPC_PORT=#{data_bag_item('anypay', 'api')['ZEN_RPC_PORT']}",
      "COIN_TEXT_API_KEY=#{data_bag_item('anypay', 'api')['COIN_TEXT_API_KEY']}",
      "STATSD_HOST=#{data_bag_item('anypay', 'api')['STATSD_HOST']}",
      "SUDO_PASSWORD_HASH=#{data_bag_item('anypay', 'api')['SUDO_PASSWORD_HASH']}",
      "UPTIMEROBOT_API_KEY=#{data_bag_item('anypay', 'api')['UPTIMEROBOT_API_KEY']}",
      "DASH_ZEROMQ_URL=#{data_bag_item('anypay', 'api')['DASH_ZEROMQ_URL']}",
      "BLOCKCYPHER_DASH_FEE=#{data_bag_item('anypay', 'api')['BLOCKCYPHER_DASH_FEE']}",
      "COINMARKETCAP_API_KEY=#{data_bag_item('anypay', 'api')['COINMARKETCAP_API_KEY']}",
      "ZEC_FORWARDING_URL=#{data_bag_item('anypay', 'api')['ZEC_FORWARDING_URL']}",
      "LTC_FORWARDING_URL=#{data_bag_item('anypay', 'api')['LTC_FORWARDING_URL']}",
      "DOGE_FORWARDING_URL=#{data_bag_item('anypay', 'api')['DOGE_FORWARDING_URL']}",
      "GOOGLE_MAPS_API_KEY=#{data_bag_item('anypay', 'api')['GOOGLE_MAPS_API_KEY']}",
      "SMART_FORWARDING_URL=#{data_bag_item('anypay', 'api')['SMART_FORWARDING_URL']}",
      "RVN_FORWARDING_URL=#{data_bag_item('anypay', 'api')['RVN_FORWARDING_URL']}",
      "MONITOR_BASE=#{data_bag_item('anypay', 'api')['MONITOR_BASE']}",
      "ZEC_FORWARDER_BASE=#{data_bag_item('anypay', 'api')['ZEC_FORWARDER_BASE']}",
      "DASH_CORE_HOST=#{data_bag_item('anypay', 'api')['DASH_CORE_HOST']}",
      "DASH_CORE_PORT=#{data_bag_item('anypay', 'api')['DASH_CORE_PORT']}",
      "DASH_CORE_USER=#{data_bag_item('anypay', 'api')['DASH_CORE_USER']}",
      "DASH_CORE_PASSWORD=#{data_bag_item('anypay', 'api')['DASH_CORE_PASSWORD']}",
      "DASH_RPC_HOST=#{data_bag_item('anypay', 'api')['DASH_RPC_HOST']}",
      "DASH_RPC_PORT=#{data_bag_item('anypay', 'api')['DASH_RPC_PORT']}",
      "DASH_RPC_USER=#{data_bag_item('anypay', 'api')['DASH_RPC_USER']}",
      "DASHTEXT_TOKEN=#{data_bag_item('anypay', 'api')['DASHTEXT_TOKEN']}",
      "ZEC_RPC_PASSWORD=#{data_bag_item('anypay', 'api')['ZEC_RPC_PASSWORD']}",
      "ZEC_RPC_USER=#{data_bag_item('anypay', 'api')['ZEC_RPC_USER']}",
      "ZEC_RPC_PORT=#{data_bag_item('anypay', 'api')['ZEC_RPC_PORT']}",
      "ZEC_RPC_HOST=#{data_bag_item('anypay', 'api')['ZEC_RPC_HOST']}",
      "DASH_RPC_PASSWORD=#{data_bag_item('anypay', 'api')['DASH_RPC_PASSWORD']}",
      "BCH_FORWARD_CALLBACK_URL=#{data_bag_item('anypay', 'api')['BCH_FORWARD_CALLBACK_URL']}",
      "API_BASE=#{data_bag_item('anypay', 'api')['API_BASE']}",
      "BSV_RPC_HOST=#{data_bag_item('router', 'bsv')['BSV_RPC_HOST']}",
      "BSV_RPC_PORT=#{data_bag_item('router', 'bsv')['BSV_RPC_PORT']}",
      "BSV_RPC_USER=#{data_bag_item('router', 'bsv')['BSV_RPC_USER']}",
      "BSV_RPC_PASSWORD=#{data_bag_item('router', 'bsv')['BSV_RPC_PASSWORD']}",
      "BTC_RPC_HOST=#{data_bag_item('btc', 'router')['BTC_RPC_HOST']}",
      "BTC_RPC_PORT=#{data_bag_item('btc', 'router')['BTC_RPC_PORT']}",
      "BTC_RPC_USER=#{data_bag_item('btc', 'router')['BTC_RPC_USER']}",
      "BTC_RPC_PASSWORD=#{data_bag_item('btc', 'router')['BTC_RPC_PASSWORD']}",
      "BTC_HD_PUBLIC_KEY=#{data_bag_item('btc', 'router')['BTC_HD_PUBLIC_KEY']}",
      "JSON_PROTOCOL_IDENTITY_ADDRESS=#{data_bag_item('anypay', 'api')['JSON_PROTOCOL_IDENTITY_ADDRESS']}",
      "JSON_PROTOCOL_IDENTITY_WIF=#{data_bag_item('anypay', 'api')['JSON_PROTOCOL_IDENTITY_WIF']}",
      "BSV_HD_PUBLIC_KEY=#{data_bag_item('router','bsv')['BSV_HD_PUBLIC_KEY']}",
      "BCH_HD_PUBLIC_KEY=#{data_bag_item('router', 'bch')['BCH_HD_PUBLIC_KEY']}",
      "DASH_HD_PUBLIC_KEY=#{data_bag_item('router', 'dash')['DASH_HD_PUBLIC_KEY']}",
      "API_BASE=https://api.anypayinc.com",
      "BIP_270_EXTRA_OUTPUT_ADDRESS=1Q9Z2y3Jhq6xbxD6AU34StgmUjfpbZgxqA",
      "BIP_270_DASH_EXTRA_OUTPUT_ADDRESS=XhdakBbwz1hxHkNQWjfzkjukZTFV2umkzP",
      "X509_DOMAIN_CERT_DER_PATH=#{data_bag_item('anypayinc', 'x509')['X509_DOMAIN_CERT_DER_PATH']}",
      "X509_ROOT_CERT_DER_PATH=#{data_bag_item('anypayinc', 'x509')['X509_ROOT_CERT_DER_PATH']}",
      "X509_PRIVATE_KEY_PATH=#{data_bag_item('anypayinc', 'x509')['X509_PRIVATE_KEY_PATH']}",
      "MONEYBUTTON_WEBHOOK_SECRET=#{data_bag_item('anypayinc', 'moneybutton')['webhook_secret']}",
      "USDH_HD_PUBLIC_KEY=#{data_bag_item('router', 'bch')['BCH_HD_PUBLIC_KEY']}",
      "CASHBACK_BCH_PRIVATE_KEY=#{data_bag_item('cashback', 'bch')['PRIVATE_KEY']}"
    ]
  end

end
