{
 "title": "NodeJS Application Logs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Log Errors",
   "type": "timeseries",
   "description": "Per Minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({level=\"error\"} |= `` [1m])"
    }
   ]
  },
  {
   "title": "Log Info",
   "type": "timeseries",
   "description": "Per Minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({level=\"info\"} |= `` [1m])"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "description": "Live tail of logs sortable by error",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{level=\"error\"} |= ``"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "logs",
   "description": "Live tail of logs sortable by error",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{level=\"info\"} |= ``"
    }
   ]
  }
 ]
}