version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: circleci/node:16
      - image: circleci/postgres:9.5-postgis
        environment:
          POSTGRES_USER: anypay_test
          POSTGRES_DB: anypay_test
          POSTGRES_PASSWORD: "letmein"
      - image: rabbitmq:3
    services:
      rabbitmq:
        image: rabbitmq:latest
        options: -p 5672:5672 -p 15672:15672
        ports:
          - 5672:5672
          - 15672:15672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        options: --health-cmd "rabbitmqctl wait /var/lib/rabbitmq/mnesia/rabbit@localhost.pid"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Migrate & Seed Test Database
          command: npm run db:migrate
      - run:
          name: Seed Prices
          command: npm run db:seed:prices
      - run:
          name: Run Model Tests
          command: npm run test:models
      - run:
          name: Run Lib Tests
          command: npm run test:lib
      - run:
          name: Run Integration Tests
          command: npm run test:integration
      - run:
          name: Report Code Coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov

  deploy:
    machine: true
    steps:
      - run:
          name: Deploy to Web Servers
          command: ssh root@anypayx.com "/opt/deploy_anypay_api_production.sh"

  deploy_develop:
    machine: true
    steps:
      - run:
          name: Deploy Develop Branch To Develop Web Server
          command: ssh root@develop.anypayx.com "/opt/deploy_anypay_api_develop.sh"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only:
                - develop

