version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          JOBS: 1
    steps:
      - checkout

      - setup_remote_docker:
          filters:
            branches:
              only:
                - master
                - staging
      - run:
          name: Build docker image
          command: docker build -t anypay .

      - add_ssh_keys

  deploy:
    command: |
      ./push_to_docker.sh
      ssh chef@api.anypay.global "sudo /opt/anypay/deploy_api.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master

