version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          JOBS: 1
    steps:
      - checkout

      - setup_remote_docker:
          filters:
            branches:
              only:
                - master
                - staging
      - run:
          name: Build docker image
          command: docker build -t anypay .

      - add_ssh_keys

      - deploy:
          command: |
            ./push_to_docker_staging.sh
            ssh chef@api.staging.anypay.global "sudo /opt/anypay/redeploy_api_staging.sh"
