version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay .
      - add_ssh_keys
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test writing payment output
          command: mocha --require=ts-node/register --timeout=10000 test/lib/payment_processor.ts  
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay .
      - run:
          name: Deploy To Server
          command: |
            ./push_to_docker.sh
            ssh chef@api.anypay.global "sudo /opt/anypay/deploy_api.sh"

  deploy_staging:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay .
      - run:
          name: Deploy To Server
          command: |
            ./push_to_docker_staging.sh
            ssh chef@api.staging.anypay.global "sudo /opt/anypay/deploy_api.sh"

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

  build-and-deploy-staging:
      jobs:
        - build
        - deploy_staging:
            requires:
              - build
            filters:
              branches:
                only: staging
