version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: circleci/node:14
      - image: circleci/postgres:9.5-postgis
        environment:
          POSTGRES_USER: anypay_test
          POSTGRES_DB: anypay_test
          POSTGRES_PASSWORD: "letmein"
      - image: rabbitmq:3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Migrate & Seed Test Database
          command: npm run db:migrate
      - run:
          name: Seed Prices
          command: npm run db:seed:prices
      - run:
          name: Run Main Tests
          command: npm test
            #- coveralls/upload:
            #path_to_lcov: ./coverage
      - run:
          name: Report Code Coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov

  build_docker:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay . 
      - run:
          name: Push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD 
            docker tag anypay anypay/anypay:$CIRCLE_BRANCH
            docker push anypay/anypay:$CIRCLE_BRANCH

  deploy:
    machine: true
    steps:
      - run:
          name: Deploy to Web Servers
          command: ssh ubuntu@api.next.anypayx.com "sudo chef-client -o recipe[anypay::api_next]"

  deploy_beta:
    machine: true
    steps:
      - run:
          name: Deploy Develop Branch To Beta Web Server
          command: ssh beta.anypayx.com "sudo chef-client -o recipe[anypay_api::beta]"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_docker:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master
      - deploy_beta:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - develop

