version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Migrate & Seed Test Database
          command: npm run db:migrate
      - run:
          name: Run Main Tests
          command: npm test
      - run:
          name: Run Payment Request Tests
          command: npm run payreq:test 

  build_docker:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay . 
      - run:
          name: Push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD 
            docker tag anypay anypay/anypay:$CIRCLE_BRANCH
            docker push anypay/anypay:$CIRCLE_BRANCH

  deploy:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run:
          name: Deploy to Web Servers
          command: echo "no deploy"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build_docker:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master

