version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay .
      - add_ssh_keys
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Running tests
          command: npm test  
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay .
      - run:
          name: Deploy To Server
          command: |
            ./push_to_docker.sh
            ssh -o StrictHostKeyChecking=no chef@api.anypay.global "sudo /opt/anypay/deploy_api.sh"
  deploy_staging:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay .
      - run:
          name: Deploy To Server
          command: |
            ./push_to_docker_staging.sh
            ssh -o StrictHostKeyChecking=no chef@api.staging.anypay.global "sudo /opt/anypay/deploy_api.sh"
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

  build-and-deploy-staging:
      jobs:
        - build
        - test:
            requires:
              - build
            filters:
              branches:
                only: staging
        - deploy_staging:
            requires:
              - build
            filters:
              branches:
                only: staging
