version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:9.5-postgis
        environment:
          POSTGRES_USER: anypay_test
          POSTGRES_DB: anypay_test
          POSTGRES_PASSWORD: "letmein"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Migrate & Seed Test Database
          command: npm run db:migrate
      - run:
          name: Seed Prices
          command: npm run db:seed:prices
      - run:
          name: Run Main Tests
          command: npm test
      - run:
          name: Run Payment Request Tests
          command: npm run payreq:test 

  build_docker:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay . 
      - run:
          name: Push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD 
            docker tag anypay anypay/anypay:$CIRCLE_BRANCH
            docker push anypay/anypay:$CIRCLE_BRANCH

  deploy:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run:
          name: Deploy to Web Servers
          command: echo "no deploy"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_docker:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master

