global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'my_target'
    static_configs:
      - targets: ['localhost:5211']
    metrics_path: '/_metrics'
    basic_auth:
      username: 'prometheus'
      password: 'password'

