name: Build and Deploy

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: circleci/postgres:9.5-postgis
        env:
          POSTGRES_USER: anypay_test
          POSTGRES_DB: anypay_test
          POSTGRES_PASSWORD: letmein

      rabbitmq:
        image: rabbitmq:3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Migrate & Seed Test Database
        run: npm run db:migrate

      - name: Seed Prices
        run: npm run db:seed:prices

      - name: Run Model Tests
        run: npm run test:models

      - name: Run Lib Tests
        run: npm run test:lib

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Report Code Coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build docker image
        run: docker build -t anypay .

      - name: Push to Docker Hub
        run: |
          docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker tag anypay anypay/anypay:${{ github.event_name }}

          if [ "${{ github.event_name }}" = "push" ]; then
            docker push anypay/anypay:${{ github.ref_name }}
          fi

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to Web Servers
        run: ssh ubuntu@api.next.anypayx.com "sudo chef-client -o recipe[anypay::api_next]"

  deploy_develop:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Deploy Develop Branch To Beta Web Server
        run: ssh root@develop.anypayx.com "/opt/deploy_anypay_api.sh"

