name: Build and Deploy

on: push

env:
  POSTGRES_USER: anypay_test
  POSTGRES_DB: anypay_test
  POSTGRES_PASSWORD: letmein

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    services:
      postgres:
        image: postgres:9.5-postgis
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
      rabbitmq:
        image: rabbitmq:3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Migrate & Seed Test Database
      run: npm run db:migrate

    - name: Seed Prices
      run: npm run db:seed:prices

    - name: Run Model Tests
      run: npm run test:models

    - name: Run Lib Tests
      run: npm run test:lib

    - name: Run Integration Tests
      run: npm run test:integration

    - name: Report Code Coverage
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov

  build_docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      run: docker setup

    - name: Build Docker image
      run: docker build -t anypay .

    - name: Push to Docker Hub
      run: |
        docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker tag anypay anypay/anypay:${{ github.ref }}
        docker push anypay/anypay:${{ github.ref }}

  deploy:
    needs: build_docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Deploy to Web Servers
      run: ssh ubuntu@api.next.anypayx.com "sudo chef-client -o recipe[anypay::api_next]"

  deploy_beta:
    needs: build_docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - name: Deploy Develop Branch To Beta Web Server
      run: ssh root@ionia.anypayx.com "/opt/deploy_anypay_api.sh"

